### ISSUE TITLE
README not updated

### ISSUE THREAD

**Issue by Adam2092** [martincukal/DIT168#1]
- Instructions of "./main" is no longer matching the executable files ("communication.XXX").
- Lack of instruction about Docker usage.

From Yue Kang

**Comment by martincukal** [comment]
Fixed the readme, docker usage is explained in the Contributing.md thats how it was stated in the assignment or should i also include it in readme ?

**Comment by Adam2092** [comment]
Contributing.md checked. Personally I would suggest that you state this part in readme, given that generating a docker image from your code doesn't count much as contributing to your project.

**Comment by martincukal** [comment]
Updated it.

**Comment by Adam2092** [comment]
Great, appreciate it very much.
